server:
  port: 8089
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  profiles:
    active:
      - group_dev

---
spring:
  profiles:
    group:
      - group_dev: dev
      - group_prod: prod

---
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    generate-unique-name: false
    name: library
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:library
    username: bookworm
    password: william
    # tcp: jdbc:h2:tcp://localhost:9092/mem:voting
  h2:
    console:
      enabled: true

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

---
spring:
  config:
    activate:
      on-profile: prod


  security:
    oauth2:
      client:
        registration:
          github:
            clientId: github-client-id
            clientSecret: github-client-secret
            scope: email, public_profile
  data:
    rest:
      base-path: /api
      return-body-on-create: true
      default-page-size: 20

management:
  endpoints:
    web:
      exposure:
        include: [beans, health, metrics, env]

logging:
  file:
    path: /info/logs/
    name: taco.log
  level:
    root: INFO
    org.springframework.security: DEBUG
---
logging:
  level:
    root: WARN
    by.anthony.hateoasexample: DEBUG
    org.springframework.security.web.FilterChainProxy: DEBUG

taco:
  orders:
    pageSize: 10




  datasource:
    url: jdbc:mysql://localhost/tacocloud
    username: tacouser
    password: tacopassword
  logging:
    level:
      tacos: WARN